[2023-07-22T00:29:20.099+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2023-07-21T00:00:00+00:00 [queued]>
[2023-07-22T00:29:20.105+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2023-07-21T00:00:00+00:00 [queued]>
[2023-07-22T00:29:20.106+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-07-22T00:29:20.106+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-07-22T00:29:20.106+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-07-22T00:29:20.119+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2023-07-21 00:00:00+00:00
[2023-07-22T00:29:20.124+0000] {standard_task_runner.py:55} INFO - Started process 16084 to run task
[2023-07-22T00:29:20.129+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'scheduled__2023-07-21T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpv3yanv9k']
[2023-07-22T00:29:20.131+0000] {standard_task_runner.py:83} INFO - Job 15: Subtask create_table
[2023-07-22T00:29:20.229+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table scheduled__2023-07-21T00:00:00+00:00 [running]> on host 9d876987b8ed
[2023-07-22T00:29:20.330+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-07-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-21T00:00:00+00:00
[2023-07-22T00:29:20.347+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-07-22T00:29:20.354+0000] {sql.py:315} INFO - Running statement: 
            DROP TABLE IF EXISTS users;
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        , parameters: None
[2023-07-22T00:29:20.382+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20230721T000000, start_date=20230722T002920, end_date=20230722T002920
[2023-07-22T00:29:20.425+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-07-22T00:29:20.459+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-07-22T04:13:14.108+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2023-07-21T00:00:00+00:00 [queued]>
[2023-07-22T04:13:14.120+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2023-07-21T00:00:00+00:00 [queued]>
[2023-07-22T04:13:14.121+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-07-22T04:13:14.121+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-07-22T04:13:14.121+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-07-22T04:13:14.132+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2023-07-21 00:00:00+00:00
[2023-07-22T04:13:14.140+0000] {standard_task_runner.py:55} INFO - Started process 115 to run task
[2023-07-22T04:13:14.143+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'scheduled__2023-07-21T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpi55e38j6']
[2023-07-22T04:13:14.145+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask create_table
[2023-07-22T04:13:14.268+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table scheduled__2023-07-21T00:00:00+00:00 [running]> on host ef71d3f52879
[2023-07-22T04:13:14.347+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-07-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-21T00:00:00+00:00
[2023-07-22T04:13:14.364+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 288, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 88, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 70, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 432, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres` isn't defined
[2023-07-22T04:13:14.367+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=user_processing, task_id=create_table, execution_date=20230721T000000, start_date=20230722T041314, end_date=20230722T041314
[2023-07-22T04:13:14.374+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task create_table (The conn_id `postgres` isn't defined; 115)
[2023-07-22T04:13:14.395+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-07-22T04:13:14.422+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-22T05:54:14.278+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2023-07-21T00:00:00+00:00 [queued]>
[2023-07-22T05:54:14.435+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2023-07-21T00:00:00+00:00 [queued]>
[2023-07-22T05:54:14.464+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-07-22T05:54:14.483+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-07-22T05:54:14.483+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-07-22T05:54:14.564+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2023-07-21 00:00:00+00:00
[2023-07-22T05:54:14.577+0000] {standard_task_runner.py:55} INFO - Started process 5170 to run task
[2023-07-22T05:54:14.636+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'scheduled__2023-07-21T00:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpnoh3bf_2']
[2023-07-22T05:54:14.661+0000] {standard_task_runner.py:83} INFO - Job 45: Subtask create_table
[2023-07-22T05:54:14.974+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table scheduled__2023-07-21T00:00:00+00:00 [running]> on host ef71d3f52879
[2023-07-22T05:54:15.157+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-07-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-21T00:00:00+00:00
[2023-07-22T05:54:15.186+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-07-22T05:54:15.204+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        , parameters: None
[2023-07-22T05:54:15.207+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2023-07-22T05:54:15.233+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20230721T000000, start_date=20230722T055414, end_date=20230722T055415
[2023-07-22T05:54:15.333+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-07-22T05:54:15.416+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-07-22T05:56:55.587+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2023-07-21T00:00:00+00:00 [queued]>
[2023-07-22T05:56:55.630+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2023-07-21T00:00:00+00:00 [queued]>
[2023-07-22T05:56:55.631+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-07-22T05:56:55.631+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-07-22T05:56:55.631+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-07-22T05:56:55.714+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2023-07-21 00:00:00+00:00
[2023-07-22T05:56:55.756+0000] {standard_task_runner.py:55} INFO - Started process 5462 to run task
[2023-07-22T05:56:55.815+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'scheduled__2023-07-21T00:00:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp0rt6raeg']
[2023-07-22T05:56:55.836+0000] {standard_task_runner.py:83} INFO - Job 105: Subtask create_table
[2023-07-22T05:56:56.119+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table scheduled__2023-07-21T00:00:00+00:00 [running]> on host ef71d3f52879
[2023-07-22T05:56:56.398+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-07-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-21T00:00:00+00:00
[2023-07-22T05:56:56.438+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-07-22T05:56:56.452+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        , parameters: None
[2023-07-22T05:56:56.463+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2023-07-22T05:56:56.493+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20230721T000000, start_date=20230722T055655, end_date=20230722T055656
[2023-07-22T05:56:56.553+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-07-22T05:56:56.664+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
